// <auto-generated />
using System;
using AirlineDataV2.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineDataV2.Migrations
{
    [DbContext(typeof(AirlineDbContext))]
    partial class AirlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineDataV2.DbModels.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UcakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UcakId");

                    b.ToTable("BakimKayitlari");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.BakimPersonel", b =>
                {
                    b.Property<int>("BakimId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("BakimId", "PersonelId");

                    b.HasIndex("PersonelId");

                    b.ToTable("BakimPersonel");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.Ucak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KuyrukNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ucaklar");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.BakimKaydi", b =>
                {
                    b.HasOne("AirlineDataV2.DbModels.Ucak", "Ucak")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("UcakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucak");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.BakimPersonel", b =>
                {
                    b.HasOne("AirlineDataV2.DbModels.BakimKaydi", "BakimKaydi")
                        .WithMany("BakimPersoneller")
                        .HasForeignKey("BakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineDataV2.DbModels.Personel", "Personel")
                        .WithMany("BakimPersoneller")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimKaydi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.BakimKaydi", b =>
                {
                    b.Navigation("BakimPersoneller");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.Personel", b =>
                {
                    b.Navigation("BakimPersoneller");
                });

            modelBuilder.Entity("AirlineDataV2.DbModels.Ucak", b =>
                {
                    b.Navigation("BakimKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
